// Generated by gencpp from file tomato_slam/TomatoDetection.msg
// DO NOT EDIT!


#ifndef TOMATO_SLAM_MESSAGE_TOMATODETECTION_H
#define TOMATO_SLAM_MESSAGE_TOMATODETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tomato_slam
{
template <class ContainerAllocator>
struct TomatoDetection_
{
  typedef TomatoDetection_<ContainerAllocator> Type;

  TomatoDetection_()
    : position()
    , radius(0.0)
    , confidence(0.0)  {
    }
  TomatoDetection_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , radius(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::tomato_slam::TomatoDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tomato_slam::TomatoDetection_<ContainerAllocator> const> ConstPtr;

}; // struct TomatoDetection_

typedef ::tomato_slam::TomatoDetection_<std::allocator<void> > TomatoDetection;

typedef boost::shared_ptr< ::tomato_slam::TomatoDetection > TomatoDetectionPtr;
typedef boost::shared_ptr< ::tomato_slam::TomatoDetection const> TomatoDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tomato_slam::TomatoDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tomato_slam::TomatoDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tomato_slam::TomatoDetection_<ContainerAllocator1> & lhs, const ::tomato_slam::TomatoDetection_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.radius == rhs.radius &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tomato_slam::TomatoDetection_<ContainerAllocator1> & lhs, const ::tomato_slam::TomatoDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tomato_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_slam::TomatoDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_slam::TomatoDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_slam::TomatoDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9023f05a2180cc99be40075822ec995";
  }

  static const char* value(const ::tomato_slam::TomatoDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9023f05a2180cc9ULL;
  static const uint64_t static_value2 = 0x9be40075822ec995ULL;
};

template<class ContainerAllocator>
struct DataType< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tomato_slam/TomatoDetection";
  }

  static const char* value(const ::tomato_slam::TomatoDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 番茄检测消息\n"
"geometry_msgs/Point position  # 番茄中心位置\n"
"float32 radius               # 番茄半径\n"
"float32 confidence           # 检测置信度\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tomato_slam::TomatoDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.radius);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TomatoDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tomato_slam::TomatoDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tomato_slam::TomatoDetection_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOMATO_SLAM_MESSAGE_TOMATODETECTION_H
