// Generated by gencpp from file tomato_slam/TomatoDetections.msg
// DO NOT EDIT!


#ifndef TOMATO_SLAM_MESSAGE_TOMATODETECTIONS_H
#define TOMATO_SLAM_MESSAGE_TOMATODETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tomato_slam/TomatoDetection.h>

namespace tomato_slam
{
template <class ContainerAllocator>
struct TomatoDetections_
{
  typedef TomatoDetections_<ContainerAllocator> Type;

  TomatoDetections_()
    : header()
    , detections()  {
    }
  TomatoDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tomato_slam::TomatoDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tomato_slam::TomatoDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::tomato_slam::TomatoDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tomato_slam::TomatoDetections_<ContainerAllocator> const> ConstPtr;

}; // struct TomatoDetections_

typedef ::tomato_slam::TomatoDetections_<std::allocator<void> > TomatoDetections;

typedef boost::shared_ptr< ::tomato_slam::TomatoDetections > TomatoDetectionsPtr;
typedef boost::shared_ptr< ::tomato_slam::TomatoDetections const> TomatoDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tomato_slam::TomatoDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tomato_slam::TomatoDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tomato_slam::TomatoDetections_<ContainerAllocator1> & lhs, const ::tomato_slam::TomatoDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tomato_slam::TomatoDetections_<ContainerAllocator1> & lhs, const ::tomato_slam::TomatoDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tomato_slam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tomato_slam::TomatoDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tomato_slam::TomatoDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tomato_slam::TomatoDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c67131f4672dd62f883ff3c6bb318393";
  }

  static const char* value(const ::tomato_slam::TomatoDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc67131f4672dd62fULL;
  static const uint64_t static_value2 = 0x883ff3c6bb318393ULL;
};

template<class ContainerAllocator>
struct DataType< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tomato_slam/TomatoDetections";
  }

  static const char* value(const ::tomato_slam::TomatoDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 多番茄检测消息\n"
"Header header\n"
"tomato_slam/TomatoDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tomato_slam/TomatoDetection\n"
"# 番茄检测消息\n"
"geometry_msgs/Point position  # 番茄中心位置\n"
"float32 radius               # 番茄半径\n"
"float32 confidence           # 检测置信度\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tomato_slam::TomatoDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TomatoDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tomato_slam::TomatoDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tomato_slam::TomatoDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tomato_slam::TomatoDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOMATO_SLAM_MESSAGE_TOMATODETECTIONS_H
